using System.IO;
using System.Text;
using DisasmStudio.Core.Analysis;
using DisasmStudio.Core.Disasm;
using DisasmStudio.Core.IL;

namespace DisasmStudio.Core.Export;

/// <summary>
/// Writes the analysis out as text: the full (or per-function) disassembly listing as <c>.asm</c>, or
/// the decompiler's Pseudo-C as <c>.c</c>. Everything streams straight to a <see cref="TextWriter"/>
/// so even a multi-million-line listing never builds a giant string in memory. The shared
/// decoder/formatter are created per call, so an export can run on a background thread.
/// </summary>
public static class SourceExporter
{
    // ---- disassembly (.asm) ----

    /// <summary>Write the entire linear listing. Routes through the architecture-neutral decoder seam, so it
    /// handles both x86/x64 (Iced) and ARM/Thumb/AArch64 (Capstone) images with identical output.</summary>
    public static void WriteAsm(TextWriter w, AnalysisResult r, IProgress<int>? progress = null, CancellationToken ct = default)
    {
        var dis = NeutralDisasm.For(r.Image, r.Names);
        try
        {
            int digits = AddrDigits(r);
            WriteAsmHeader(w, r);

            long count = r.Linear.Count;
            for (long i = 0; i < count; i++)
            {
                if ((i & 0xFFFF) == 0) { ct.ThrowIfCancellationRequested(); progress?.Report((int)(i * 100 / Math.Max(1, count))); }
                ulong va = r.Linear.VaAt(i);
                MaybeLabel(w, r, va, digits);
                WriteAsmLine(w, r, dis, i, va, digits);
            }
        }
        finally { (dis as IDisposable)?.Dispose(); }   // the ARM (Capstone) decoder is disposable; the Iced one is not
    }

    /// <summary>Write only the instructions belonging to one function (up to the next function start).</summary>
    public static void WriteAsmFunction(TextWriter w, AnalysisResult r, Function fn)
    {
        var dis = NeutralDisasm.For(r.Image, r.Names);
        try
        {
            int digits = AddrDigits(r);

            // Bound the listing to the function's own reachable extent — not the rest of the image (which
            // is what an unbounded "next function start" would do for the highest-address function).
            CfgBuilder.Build(r.Image, fn, r.JumpTables);
            ulong end = fn.Va + 1;
            foreach (var bb in fn.Blocks) if (bb.End > end) end = bb.End;
            foreach (var f in r.Functions) if (f.Va > fn.Va && f.Va < end) end = f.Va;   // stop early if functions overlap

            w.WriteLine($"; {fn.Name}  @ {fn.Va:X}");
            long start = r.Linear.IndexOf(fn.Va);
            for (long i = start; i < r.Linear.Count; i++)
            {
                ulong va = r.Linear.VaAt(i);
                if (va >= end) break;
                if (i != start) MaybeLabel(w, r, va, digits);
                WriteAsmLine(w, r, dis, i, va, digits);
            }
        }
        finally { (dis as IDisposable)?.Dispose(); }
    }

    private static void WriteAsmHeader(TextWriter w, AnalysisResult r)
    {
        w.WriteLine($"; Disassembly of {Path.GetFileName(r.Image.FilePath)}  ({r.Image.FormatName}, {r.Image.ArchName}, base {r.Image.ImageBase:X})");
        w.WriteLine($"; {r.Functions.Count} functions — generated by DisasmStudio");
        w.WriteLine();
    }

    private static void MaybeLabel(TextWriter w, AnalysisResult r, ulong va, int digits)
    {
        if (r.Image.IsExecutableVa(va) && r.Names.TryGetValue(va, out var name))
            w.WriteLine($"\n{name}:");
    }

    private static void WriteAsmLine(TextWriter w, AnalysisResult r, INeutralDisassembler dis, long line, ulong va, int digits)
    {
        string addr = va.ToString("X" + digits);
        if (r.Linear.IsDataAt(line))
        {
            long len = line + 1 < r.Linear.Count ? (long)(r.Linear.VaAt(line + 1) - va) : 1;
            var bytes = r.Image.ReadBytesAtVa(va, (int)Math.Clamp(len, 1, 256));
            // ARM firmware holds numeric tables in the printable range; require a run longer than a word
            // before quoting one as a string, so a lone printable dword stays bytes. x86/x64 keeps min 3.
            w.WriteLine($"{addr}    {DataText(bytes, r.Image.IsArm ? 5 : 3)}");
            return;
        }
        var toks = dis.Format(va);   // reused between calls — concatenate now, before the next Format
        if (toks.Count == 0) { w.WriteLine($"{addr}    ??"); return; }
        string text = string.Concat(toks.Select(t => t.Text));
        if (r.Comments.TryGetValue(va, out var c)) text += "   ; " + c;
        w.WriteLine($"{addr}    {text}");
    }

    private static string DataText(byte[] b, int minLen = 3)
    {
        if (TryString(b, minLen, out var s)) return $"db {s}";
        var parts = b.Take(16).Select(x => $"0x{x:X2}");
        return "db " + string.Join(", ", parts) + (b.Length > 16 ? ", …" : "");
    }

    private static bool TryString(byte[] b, int minLen, out string text)
    {
        text = "";
        if (b.Length < minLen) return false;
        bool ascii = true;
        for (int i = 0; i < b.Length; i++)
            if (b[i] is not (>= 0x20 and < 0x7F or 0x09) && !(b[i] == 0 && i == b.Length - 1)) { ascii = false; break; }
        if (!ascii) return false;
        var sb = new System.Text.StringBuilder("\"");
        foreach (var c in b) { if (c == 0) break; sb.Append(c is >= 0x20 and < 0x7F ? (char)c : '.'); }
        sb.Append('"');
        text = sb.ToString();
        return true;
    }

    private static int AddrDigits(AnalysisResult r) => Math.Max(8, r.Image.MaxVa.ToString("X").Length);

    // ---- decompiled Pseudo-C (.c) ----

    /// <summary>Write the Pseudo-C of every discovered function.</summary>
    public static void WriteC(TextWriter w, AnalysisResult r, IProgress<int>? progress = null, CancellationToken ct = default)
    {
        w.WriteLine($"// Pseudo-C of {Path.GetFileName(r.Image.FilePath)}  ({r.Image.FormatName}, {r.Image.ArchName})");
        w.WriteLine($"// {r.Functions.Count} functions — generated by DisasmStudio (best-effort decompilation)");
        w.WriteLine();

        int n = r.Functions.Count, i = 0;
        foreach (var fn in r.Functions)
        {
            if ((i & 0x3F) == 0) { ct.ThrowIfCancellationRequested(); progress?.Report(i * 100 / Math.Max(1, n)); }
            WriteCBody(w, Decompiler.Decompile(fn, r));
            w.WriteLine();
            i++;
        }
    }

    /// <summary>Write the Pseudo-C of one function.</summary>
    public static void WriteCFunction(TextWriter w, AnalysisResult r, Function fn) => WriteCBody(w, Decompiler.Decompile(fn, r));

    private static void WriteCBody(TextWriter w, DecompiledFunction dc)
    {
        foreach (var ln in dc.PseudoC)
            w.WriteLine(new string(' ', ln.Indent * 4) + string.Concat(ln.Tokens.Select(t => t.Text)));
    }

    // ---- compilable C (.c) ----
    // A self-contained file that compiles (cl /c): a generated preamble declares the CPU registers as
    // integer globals, the placeholder helpers (__icall / flags / __rol) and forward prototypes for
    // every function; the bodies use typed pointer casts, numeric addresses and sanitized names.

    /// <summary>Write a compilable C translation unit covering every function.</summary>
    public static void WriteCompilableC(TextWriter w, AnalysisResult r, IProgress<int>? progress = null, CancellationToken ct = default)
    {
        var regs = new SortedSet<string>(StringComparer.Ordinal);
        var protos = new SortedSet<string>(StringComparer.Ordinal);
        var body = new StringBuilder();

        var defined = new HashSet<string>(StringComparer.Ordinal);
        int n = r.Functions.Count, i = 0;
        foreach (var fn in r.Functions)
        {
            if ((i++ & 0x3F) == 0) { ct.ThrowIfCancellationRequested(); progress?.Report(i * 100 / Math.Max(1, n)); }
            string nm = ExprWriter.Sanitize(fn.Name);
            protos.Add(nm);
            // Two functions can share a name (duplicate symbols); only define the first to avoid a redefinition.
            if (!defined.Add(nm)) { body.Append($"/* skipped duplicate definition: {nm} */\n\n"); continue; }
            RenderCompilable(Decompiler.DecompileToCompilableC(fn, r), body, regs, protos);
            body.Append('\n');
        }
        WriteCompilablePreamble(w, regs, protos);
        w.Write(body.ToString());
    }

    /// <summary>Write a compilable C translation unit for one function.</summary>
    public static void WriteCompilableCFunction(TextWriter w, AnalysisResult r, Function fn)
    {
        var regs = new SortedSet<string>(StringComparer.Ordinal);
        var protos = new SortedSet<string>(StringComparer.Ordinal) { ExprWriter.Sanitize(fn.Name) };
        var body = new StringBuilder();
        RenderCompilable(Decompiler.DecompileToCompilableC(fn, r), body, regs, protos);
        WriteCompilablePreamble(w, regs, protos);
        w.Write(body.ToString());
    }

    private static void RenderCompilable(IReadOnlyList<DecompLine> lines, StringBuilder body, SortedSet<string> regs, SortedSet<string> protos)
    {
        var definedLabels = new HashSet<string>(StringComparer.Ordinal);
        var usedLabels = new HashSet<string>(StringComparer.Ordinal);
        var rendered = new List<string>(lines.Count);

        foreach (var ln in lines)
        {
            var t = ln.Tokens;
            for (int k = 0; k < t.Count; k++)
            {
                var tok = t[k];
                bool next = k + 1 < t.Count;
                if (tok.Kind == AsmTokenKind.Register) regs.Add(tok.Text);
                else if (tok.Kind != AsmTokenKind.Symbol) continue;
                else if (tok.Text.StartsWith("loc_"))                          // a label: definition `loc_X:` or a goto target
                    (next && t[k + 1].Text.StartsWith(":") ? definedLabels : usedLabels).Add(tok.Text);
                else if (next && t[k + 1].Text.StartsWith("(") && !tok.Text.StartsWith("__"))
                    protos.Add(tok.Text);                                       // __rol/__ror/__icall are macros/helpers
            }
            rendered.Add(new string(' ', ln.Indent * 4) + string.Concat(t.Select(x => x.Text)));
        }

        // A goto whose target block was never emitted (e.g. a depth-capped region) would be a dangling
        // label; define any such label as a no-op before the closing brace so the C still compiles.
        if (rendered.Count > 0 && rendered[^1].TrimEnd() == "}")
        {
            int at = rendered.Count - 1;
            foreach (var lbl in usedLabels) if (!definedLabels.Contains(lbl)) rendered.Insert(at++, "    " + lbl + ": ;");
        }

        foreach (var line in rendered) { body.Append(line); body.Append('\n'); }
    }

    private static void WriteCompilablePreamble(TextWriter w, SortedSet<string> regs, SortedSet<string> protos)
    {
        w.WriteLine("/* Compilable C export — generated by DisasmStudio (best-effort decompilation).");
        w.WriteLine("   Registers are modelled as independent integer globals; data addresses, indirect");
        w.WriteLine("   calls and unrecovered flags are approximated. Compiles (cl /c); not meant to run. */");
        w.WriteLine("#include <stdint.h>");
        w.WriteLine("#include <stdbool.h>");
        w.WriteLine();
        w.WriteLine("#define __rol(a, b) (a)");
        w.WriteLine("#define __ror(a, b) (a)");
        w.WriteLine("int64_t __icall();   /* indirect-call placeholder (unspecified args) */");
        w.WriteLine();
        w.WriteLine("int64_t " + string.Join(", ", ExprWriter.FlagGlobals) + ";   /* condition / unknown placeholders */");
        w.WriteLine();
        if (regs.Count > 0)
        {
            w.WriteLine("/* CPU registers referenced */");
            foreach (var grp in regs.Chunk(12)) w.WriteLine("int64_t " + string.Join(", ", grp) + ";");
            w.WriteLine();
        }
        w.WriteLine("/* function prototypes (empty parens: call arity is unchecked) */");
        foreach (var p in protos) w.WriteLine($"int64_t {p}();");
        w.WriteLine();
    }
}
